# Generated by Django 5.1.6 on 2025-02-20 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Ratings_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Pyhton', 'Pyhton'), ('java', 'java'), ('Web_Tech', 'Web_Tech'), ('SQL', 'SQL'), ('Django', 'Django'), ('JS', 'JS'), ('RESTAPI', 'RESTAPI')], max_length=50)),
                ('communication', models.CharField(choices=[('*', '*'), ('1', '1'), ('2', '2'), ('3', '3')], default=1, max_length=50)),
                ('technical', models.CharField(choices=[('*', '*'), ('1', '1'), ('2', '2'), ('3', '3')], default=1, max_length=50)),
                ('programming', models.CharField(choices=[('*', '*'), ('1', '1'), ('2', '2'), ('3', '3')], default=1, max_length=50)),
                ('remarks', models.CharField(max_length=550)),
                ('conducted_on', models.DateField(auto_now=True)),
                ('conducted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
