# Generated by Django 5.1.6 on 2025-02-18 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('course', models.CharField(choices=[('Python full stack', 'Python full stack'), ('Java full stack', 'Java full stack'), ('Mern full stack', 'Mern full stack'), ('Testing with Python', 'Testing with Python')], default='Python full stack', max_length=50)),
                ('profile_pic', models.ImageField(upload_to='student_profiles')),
                ('resume', models.FileField(upload_to='student_resumes')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
